import type { GemAttr } from "../types/guide";

export const GEM_ATTR: Record<string, GemAttr> = {
	// Skill gems
	"Wind Blast": "green",
	"Wing Blast": "green",
	"Falling Thunder": "blue",
	"Killing Palm": "green",
	"Pounce": "green",
	"Rend": "red",
	"Frost Bomb": "blue",
	"Entangle": "green",
	"Herald of Thunder": "blue",
	"Storm Wave": "blue",
	"Siphoning Strike": "green",
	"Tempest Bell": "red",
	"Hand of Chayula": "blue",
	"Wind Dancer": "green",
	"Whirling Assault": "red",
	"Charged Staff": "blue",
	"Staggering Palm": "green",
	// Support gems (subset — extend as needed)
	"Rage I": "red",
	"Rage II": "red",
	"Brink I": "red",
	"Impact Shockwave": "red",
	"Magnified Area I": "red",
	"Magnified Area II": "red",
	"Elemental Armament I": "blue",
	"Elemental Armament II": "blue",
	"Perpetual Charge": "green",
	"Shock": "blue",
	"Lightning Attunement": "blue",
	"Charge Profusion I": "green",
	"Rapid Attacks I": "green",
	"Mark of Siphoning": "green",
	"Prolonged Duration I": "blue",
	"Prolonged Duration II": "blue",
	"Thrill of the Kill": "red",
	"Thrill of the Kill II": "red",
	"Cooldown Recovery I": "green",
	"Cooldown Recovery II": "green",
	"Branching Fissures I": "blue",
	"Elemental Weakness": "blue",
	"Heightened Curse": "blue",
	"Maim": "green",
	"Pursuit II": "green",
	"Heavy Swing": "red",
	"Ancestral Call II": "red",
	"Culling Strike I": "green",
	"Innervate": "blue",
	"Retreat II": "green",
	"Multishot II": "green",
	"Longshot II": "green",
	"Blind I": "green",
	"Blazing Critical": "red",
};

export function attrFor(name: string): GemAttr {
	return GEM_ATTR[name] ?? "white";
}
